---
name: Dependabot automation

on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@5e5f99653a5b510e8555840e80cbf1514ad4af38 # v2.1.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      # This doesn't trigger an automated merge because we require at approvals
      - name: Enable auto-merge
        run: gh pr merge --auto --squash --delete-branch "${PR_URL}"
...
