name: Update Deps - NPM
on:
  schedule:
    # Sunday at 5:00pm
    - cron: "0 17 * * 0"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update NPM
        uses: actions/npm-update@v1
      - run: ./github/scripts/update-npm.sh
        env:
          id: ${{ github.run_id }}
