---
##############################
##############################
## Repository Visualization ##
##############################
##############################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

name: Repository Visualization
###########################################
# Start the job on all push or PR to main #
###########################################
on:
  push:
  #pull_request:
  #  type: [closed]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Repository Visualization
    # Set the agent to run on
    runs-on: ubuntu-latest
    timeout-minutes: 60

    ###############
    # Steps below #
    ###############
    steps:
      ############################
      # Checkout the source code #
      ############################
      - name: Checkout Code
        uses: actions/checkout@v3

      ##############################
      # Create Visualization Files #
      ##############################
      - name: Create Visualization
        uses: githubocto/repo-visualizer@0.7.1
        with:
          output_file: "./diagram.svg"
          should_push: false

      #################
      # Setup AWS cli #
      #################
      - name: Setup AWS CLI
        uses: actions/setup-aws-cli@v1
        with:
          region: ${{ secrets.AWS_REGION }}
          profile: default

      ###########################
      # Configure the AWS creds #
      ###########################
      - name: Configure AWS Credentials
        if: success()
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      ############################
      # Push the image to aws s3 #
      ############################
      - name: Push diagram to s3
        if: success()
        run: aws s3 cp diagram.svg s3://${{ secrets.AWS_BUCKET }}/diagram.svg
