---

name: Sync scala format version between Dockerfile and config file

on:
  pull_request:
    paths:
      - 'Dockerfile'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
      with:
        egress-policy: audit

    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Sync the version if the dockerfile is getting updated
      shell: bash
      run: |
        scala_version_from_dockerfile=$(grep 'scalameta/scalafmt' Dockerfile | awk -F: '{print $2}' | awk '{print $1}')
        scala_version_from_dockerfile=${scala_version_from_dockerfile#v}

        scala_version_from_config=$(grep 'version =' TEMPLATES/.scalafmt.conf | awk -F= '{print $2}' | tr -d '[:space:]')

        echo "scala_version_from_dockerfile: $scala_version_from_dockerfile"
        echo "scala_version_from_config: $scala_version_from_config"

        if [ "$scala_version_from_dockerfile" != "$scala_version_from_config" ]; then echo "versions differ"; sed -i "s/\(version =\).*/\1 ${scala_version_from_dockerfile}/g" TEMPLATES/.scalafmt.conf; fi
    - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
      with:
        add: 'TEMPLATES/.scalafmt.conf'
        fetch: false
        message: 'Update scala config version to match version installed'
